const data = [
  {
    description: "Running on Treadmill",
    time: 59,
    date: new Date("2020-06-04"),
    intensity: 7,
  },
  {
    description: "Weight Lifting",
    time: 30,
    date: new Date("2020-06-04"),
    intensity: 3,
  },
  {
    description: "Cycling To Birds Hill Park",
    time: 322,
    date: new Date("2020-07-03"),
    intensity: 13,
  },
  {
    description: "Sleeping",
    time: 600,
    date: new Date("2020-12-12"),
    intensity: 3,
  },
  {
    description: "Running on Treadmill",   
    time: 28,
    date: new Date("2021-2-6"),
    intensity: 10,
  },
  {
    description: "Rowing",   
    time: 38,
    date: new Date("2021-1-13"),
    intensity: 4,
  },
    {
    description: "Cycling",   
    time: 47,
    date: new Date("2021-1-7"),
    intensity: 12,
  },
    {
    description: "Walking",   
    time: 12,
    date: new Date("2021-2-1"),
    intensity: 11,
  },
    {
    description: "Weights",   
    time: 111,
    date: new Date("2021-1-13"),
    intensity: 7,
  },
    {
    description: "Running",   
    time: 221,
    date: new Date("2020-12-30"),
    intensity: 3,
  },
    {
    description: "Sprint",   
    time: 11,
    date: new Date("2021-2-2"),
    intensity: 15,
  },
    {
    description: "Running on Treadmill",   
    time: 21,
    date: new Date("2020-1-11"),
    intensity: 7,
  },
    {
    description: "Playing Hockey",   
    time: 39,
    date: new Date("2021-1-21"),
    intensity: 10,
  },
    {
    description: "Jogging Outside",   
    time: 87,
    date: new Date("2021-1-2"),
    intensity: 9,
  },
    {
    description: "Swimming",   
    time: 57,
    date: new Date("2020-12-22"),
    intensity: 8,
  },
    {
    description: "Jumping Jacks",   
    time: 121,
    date: new Date("2020-11-12"),
    intensity: 4,
  },
]